FROM centos:latest

WORKDIR /src

RUN yum update -y
RUN yum install -y curl
RUN curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
RUN yum install -y nodejs
RUN npm install -g node-gyp
RUN npm install -g gulp
RUN yum install -y git

ENV MYSQL_HOST 192.168.1.4
ENV JWT_SECRET abc

EXPOSE 8081

CMD ["npm", "run", "serve"]
