BUILDER_NUMBER="$0"
SETTER_TAR="setter_$BUILD_NUMBER"

SETTER_IMAGES="../public/images/uploads"
rm -rf $SETTER_IMAGES
mkdir $SETTER_IMAGES

LOCAL_SETTER_DIR="../"
LOCAL_SETTER_APP_DIR="$LOCAL_SETTER_DIR/build/app"
LOCAL_SETTER_BUILD_DIR="$LOCAL_SETTER_DIR/artifacts"
SETTER_TAR_NAME="$SETTER_TAR.tar"

cd "$LOCAL_SETTER_APP_DIR"
tar -czvf "$SETTER_TAR_NAME" "."
cp "$SETTER_TAR_NAME" "$LOCAL_SETTER_BUILD_DIR"
